# Test playbook for Ansible role cdelgehier.haproxy
---

- hosts: all
  become: true
  roles:
    - role: role_under_test
      haproxy_logrotate_managed: true 
      haproxy_errorfiles_managed: true 
