# roles/haproxy/handlers/main.yml
---

- name: reload haproxy
  service:
    name: "{{ haproxy_service }}"
    state: reloaded

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload keepalived
  service:
    name: keepalived
    state: reloaded

